version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: teller-postgres
    environment:
      POSTGRES_USER: teller
      POSTGRES_PASSWORD: teller
      POSTGRES_DB: teller_onboarding
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U teller']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
